name: superlinter
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      - name: Lint Haxe
        run: |
          haxelib install haxelint
          haxelib run haxelint -s source 
          haxelib run haxelint -s Preloader.hx